[package]
name = "ic-dbms-canister"
version = { workspace = true }
authors = { workspace = true }
categories = { workspace = true }
documentation = "https://docs.rs/ic-dbms-canister/"
edition = { workspace = true }
include = [
  "examples/**/*",
  "src/**/*",
  "../../../LICENSE",
  "README.md",
  "../../../CHANGELOG.md",
]
keywords = { workspace = true }
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
rust-version = { workspace = true }
description = "A framework to build Database canisters on the Internet Computer using DBMS, by just providing the schema."

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
ic-dbms-api = { workspace = true }
ic-dbms-macros = { workspace = true }
serde = { workspace = true }
wasm-dbms = { workspace = true }
wasm-dbms-api = { workspace = true }
wasm-dbms-macros = { workspace = true }
wasm-dbms-memory = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "read_table"
harness = false

[[bench]]
name = "eager_relation"
harness = false
