[package]
name = "wasi-dbms-memory"
version = { workspace = true }
authors = { workspace = true }
categories = ["database", "wasm"]
documentation = "https://docs.rs/wasi-dbms-memory"
edition = { workspace = true }
include = ["src/**/*", "../../../LICENSE", "README.md", "../../../CHANGELOG.md"]
keywords = ["database", "wasm", "memory", "wasi"]
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
rust-version = { workspace = true }
description = "Memory provider and page management for wasm-dbms using WASI"

[dependencies]
wasm-dbms-api = { workspace = true }
wasm-dbms-memory = { workspace = true }
