[package]
name = "wasm-dbms-api"
version = { workspace = true }
authors = { workspace = true }
categories = ["database", "wasm"]
documentation = "https://docs.rs/wasm-dbms-api/"
edition = { workspace = true }
include = [
  "src/**/*",
  "../../../LICENSE",
  "README.md",
  "../../../CHANGELOG.md",
]
keywords = ["wasm", "dbms", "database", "types"]
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
rust-version = { workspace = true }
description = "Runtime-agnostic API types and traits for the wasm-dbms DBMS engine."

[dependencies]
candid = { workspace = true, optional = true }
lazy-regex = { workspace = true }
percent-encoding = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
wasm-dbms-macros = { workspace = true }
xxhash-rust = { workspace = true }

[features]
default = []
candid = ["dep:candid"]
