[package]
name = "wasm-dbms"
version = { workspace = true }
authors = { workspace = true }
categories = ["database", "wasm"]
documentation = "https://docs.rs/wasm-dbms"
edition = { workspace = true }
include = ["src/**/*", "../../../LICENSE", "README.md", "../../../CHANGELOG.md"]
keywords = ["database", "wasm", "dbms"]
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
rust-version = { workspace = true }
description = "Runtime-agnostic DBMS engine for WASM environments"

[dependencies]
rust_decimal = { workspace = true }
wasm-dbms-api = { workspace = true }
wasm-dbms-memory = { workspace = true }
xxhash-rust = { workspace = true }

[dev-dependencies]
candid = { workspace = true }
serde = { workspace = true }
wasm-dbms-macros = { workspace = true }
wasm-dbms-memory = { workspace = true }
